[extension]
id = "vesper-blur"
name = "VesperBlur Theme"
description = "Elegant Vesper theme with native macOS transparency and blur effects"
version = "0.1.0"
schema_version = 1
authors = ["Max"]
repository = "https://github.com/max/vesper-blur-zed"

[extension.wasm]